[package]
name = "rot13"
version = "0.1.1"
authors = ["Marek Ventur <marekventur@gmail.com>"]
description = "Encodes a String as ROT13"
readme = "Readme.md"
repository = "https://github.com/marekventur/rust-rot13"
keywords = ["rot13", "rot-13"]
license = "MIT OR Apache-2.0"
